version: "3"

services:
  postgres:
    image: docker.io/postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
  keycloak:
    build:
      dockerfile: ./docker/Dockerfile.keycloak
      context: ./
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: "${PG_PASSWORD}"
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: "${KC_ADMIN_PASSWORD}"
    ports:
      - 8080:8080
    depends_on:
      - postgres
  public-client:
    build:
      dockerfile: ./docker/Dockerfile.public-client
      context: ./
    ports:
      - 5173:5173
    depends_on:
      - todo-api
      - keycloak
  todo-api:
    build:
      dockerfile: ./docker/Dockerfile.todo-api
      context: ./
    volumes:
      - todo_api_db:/db
    network_mode: "service:todo-api-proxy"
    depends_on:
      - keycloak
      - todo-api-proxy
    environment:
      KEYCLOAK_AUTH_SERVER_URL: "http://localhost:8080"
  # This is needed in the demo application as otherwise we'd have to refer to the keycloak server via the container's name, and this would result in a mismatch between `iss` claim and the actual server address.
  # We spin up an aditional NGINX container, this is not very suitable for production, but prod servers are generally never accessed via `localhost` anyway, so this issue wouldn't exist in the first place.
  todo-api-proxy:
    build:
      dockerfile: ./docker/Dockerfile.todo-api-proxy
      context: ./
    depends_on:
      - keycloak
    ports:
      - "3000:3000"

volumes:
  postgres_data:
    driver: local
  todo_api_db:
    driver: local
