version: "3"

services:
  public-client:
    build:
      dockerfile: ./docker/Dockerfile.public-client
      context: ./
      args:
        VITE_PUBLIC_CLIENT_ID: ${PUBLIC_CLIENT_ID}
        VITE_KEYCLOAK_AUTH_SERVER_REALM: ${KEYCLOAK_AUTH_SERVER_REALM}
        VITE_KEYCLOAK_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_SERVER_URL}
        VITE_API_BASE_URL: ${API_BASE_URL}
    ports:
      - "${PORT_FRONTEND}:5173"
    depends_on:
      - todo-api
    pull_policy: "build"
  todo-api:
    build:
      dockerfile: ./docker/Dockerfile.todo-api
      context: ./
    volumes:
      - todo_api_db:/db
    ports:
      - "${PORT_BACKEND}:3000"
    environment:
      KEYCLOAK_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_SERVER_URL}
      KEYCLOAK_AUTH_SERVER_REALM: ${KEYCLOAK_AUTH_SERVER_REALM}
      CONFIDENTIAL_CLIENT_ID: ${CONFIDENTIAL_CLIENT_ID}
      CONFIDENTIAL_CLIENT_SECRET: ${CONFIDENTIAL_CLIENT_SECRET}
    pull_policy: "build"

volumes:
  todo_api_db:
    driver: local
